import { WorkoutDay } from '../types';

export const workoutProgram: WorkoutDay[] = [
  {
    day: 1,
    completed: false,
    targetCalories: 250,
    exercises: [
      { id: '1-1', name: 'Push-ups', sets: 3, reps: 15, equipment: 'Bodyweight', calories: 45, description: 'Keep your body straight and lower until chest nearly touches floor' },
      { id: '1-2', name: 'Squats', sets: 3, reps: 20, equipment: 'Bodyweight', calories: 55, description: 'Keep your back straight and lower until thighs are parallel to floor' },
      { id: '1-3', name: 'Plank', sets: 3, reps: 30, equipment: 'Bodyweight', calories: 40, description: 'Hold position with body in a straight line, seconds instead of reps' },
      { id: '1-4', name: 'Jumping Jacks', sets: 3, reps: 25, equipment: 'Bodyweight', calories: 60, bpm: 120, description: 'Jump with arms and legs spread, then return to standing' },
      { id: '1-5', name: 'Mountain Climbers', sets: 3, reps: 20, equipment: 'Bodyweight', calories: 50, bpm: 100, description: 'Alternate bringing knees to chest in plank position' },
    ],
  },
  {
    day: 2,
    completed: false,
    targetCalories: 280,
    exercises: [
      { id: '2-1', name: 'Dumbbell Rows', sets: 4, reps: 12, equipment: 'Dumbbells', calories: 50, description: 'Pull dumbbell to hip while bent over' },
      { id: '2-2', name: 'Lunges', sets: 3, reps: 15, equipment: 'Bodyweight', calories: 55, description: 'Step forward and lower back knee toward ground' },
      { id: '2-3', name: 'Burpees', sets: 3, reps: 10, equipment: 'Bodyweight', calories: 70, bpm: 110, description: 'Drop to pushup, jump feet in, then jump up' },
      { id: '2-4', name: 'Bicycle Crunches', sets: 3, reps: 20, equipment: 'Bodyweight', calories: 45, description: 'Alternate elbow to opposite knee while lying on back' },
      { id: '2-5', name: 'High Knees', sets: 3, reps: 30, equipment: 'Bodyweight', calories: 60, bpm: 130, description: 'Run in place bringing knees high' },
    ],
  },
  {
    day: 3,
    completed: false,
    targetCalories: 300,
    exercises: [
      { id: '3-1', name: 'Chest Press', sets: 4, reps: 12, equipment: 'Dumbbells', calories: 60, description: 'Press dumbbells up from chest level' },
      { id: '3-2', name: 'Goblet Squats', sets: 4, reps: 15, equipment: 'Dumbbell', calories: 65, description: 'Hold dumbbell at chest and squat' },
      { id: '3-3', name: 'Russian Twists', sets: 3, reps: 25, equipment: 'Bodyweight', calories: 50, description: 'Twist torso side to side while seated' },
      { id: '3-4', name: 'Jump Squats', sets: 3, reps: 12, equipment: 'Bodyweight', calories: 65, bpm: 100, description: 'Squat then explode upward in a jump' },
      { id: '3-5', name: 'Superman', sets: 3, reps: 15, equipment: 'Bodyweight', calories: 40, description: 'Lift arms and legs while lying face down' },
    ],
  },
  {
    day: 4,
    completed: false,
    targetCalories: 260,
    exercises: [
      { id: '4-1', name: 'Pull-ups', sets: 3, reps: 8, equipment: 'Bar', calories: 55, description: 'Pull yourself up until chin is over bar' },
      { id: '4-2', name: 'Dips', sets: 3, reps: 12, equipment: 'Bar', calories: 50, description: 'Lower body by bending elbows, then push back up' },
      { id: '4-3', name: 'Wall Sit', sets: 3, reps: 45, equipment: 'Bodyweight', calories: 45, description: 'Hold squat position against wall, seconds not reps' },
      { id: '4-4', name: 'Side Plank', sets: 3, reps: 30, equipment: 'Bodyweight', calories: 40, description: 'Hold side position on elbow, per side' },
      { id: '4-5', name: 'Box Jumps', sets: 3, reps: 10, equipment: 'Box', calories: 70, description: 'Jump onto elevated surface and step down' },
    ],
  },
  {
    day: 5,
    completed: false,
    targetCalories: 290,
    exercises: [
      { id: '5-1', name: 'Deadlifts', sets: 4, reps: 10, equipment: 'Barbell', calories: 75, description: 'Lift barbell from ground to standing position' },
      { id: '5-2', name: 'Shoulder Press', sets: 3, reps: 12, equipment: 'Dumbbells', calories: 55, description: 'Press dumbbells overhead from shoulder level' },
      { id: '5-3', name: 'Leg Raises', sets: 3, reps: 15, equipment: 'Bodyweight', calories: 45, description: 'Lift legs while lying on back' },
      { id: '5-4', name: 'Speed Skaters', sets: 3, reps: 20, equipment: 'Bodyweight', calories: 60, bpm: 120, description: 'Jump side to side in skating motion' },
      { id: '5-5', name: 'Pike Push-ups', sets: 3, reps: 12, equipment: 'Bodyweight', calories: 55, description: 'Push-up with hips raised high' },
    ],
  },
  {
    day: 6,
    completed: false,
    targetCalories: 270,
    exercises: [
      { id: '6-1', name: 'Bench Press', sets: 4, reps: 10, equipment: 'Barbell', calories: 70, description: 'Press barbell from chest while lying on bench' },
      { id: '6-2', name: 'Step-ups', sets: 3, reps: 15, equipment: 'Box', calories: 60, description: 'Step up onto elevated surface, alternating legs' },
      { id: '6-3', name: 'V-ups', sets: 3, reps: 12, equipment: 'Bodyweight', calories: 50, description: 'Lift arms and legs simultaneously in V shape' },
      { id: '6-4', name: 'Battle Ropes', sets: 3, reps: 30, equipment: 'Ropes', calories: 65, bpm: 100, description: 'Create waves with heavy ropes' },
      { id: '6-5', name: 'Flutter Kicks', sets: 3, reps: 30, equipment: 'Bodyweight', calories: 45, description: 'Alternate small leg kicks while lying down' },
    ],
  },
  {
    day: 7,
    completed: false,
    targetCalories: 200,
    exercises: [
      { id: '7-1', name: 'Light Cardio', sets: 1, reps: 20, equipment: 'Bodyweight', calories: 80, description: 'Easy pace for active recovery, minutes not reps' },
      { id: '7-2', name: 'Stretching', sets: 1, reps: 15, equipment: 'Bodyweight', calories: 30, description: 'Full body stretching routine, minutes not reps' },
      { id: '7-3', name: 'Yoga Flow', sets: 1, reps: 20, equipment: 'Bodyweight', calories: 60, description: 'Light yoga poses for flexibility, minutes not reps' },
      { id: '7-4', name: 'Foam Rolling', sets: 1, reps: 10, equipment: 'Foam Roller', calories: 30, description: 'Massage muscles with foam roller, minutes not reps' },
    ],
  },
  {
    day: 8,
    completed: false,
    targetCalories: 310,
    exercises: [
      { id: '8-1', name: 'Barbell Squats', sets: 4, reps: 12, equipment: 'Barbell', calories: 80, description: 'Squat with barbell on shoulders' },
      { id: '8-2', name: 'Incline Push-ups', sets: 3, reps: 15, equipment: 'Bench', calories: 50, description: 'Push-ups with hands on elevated surface' },
      { id: '8-3', name: 'Plank to Downward Dog', sets: 3, reps: 12, equipment: 'Bodyweight', calories: 45, description: 'Move from plank to downward dog position' },
      { id: '8-4', name: 'Star Jumps', sets: 3, reps: 15, equipment: 'Bodyweight', calories: 70, bpm: 115, description: 'Jump with arms and legs forming star shape' },
      { id: '8-5', name: 'Reverse Crunches', sets: 3, reps: 20, equipment: 'Bodyweight', calories: 45, description: 'Lift hips and legs toward chest while lying down' },
    ],
  },
  {
    day: 9,
    completed: false,
    targetCalories: 320,
    exercises: [
      { id: '9-1', name: 'Bent Over Rows', sets: 4, reps: 12, equipment: 'Barbell', calories: 65, description: 'Pull barbell to chest while bent over' },
      { id: '9-2', name: 'Bulgarian Split Squats', sets: 3, reps: 12, equipment: 'Dumbbells', calories: 70, description: 'Lunge with back foot elevated' },
      { id: '9-3', name: 'Tuck Jumps', sets: 3, reps: 10, equipment: 'Bodyweight', calories: 75, bpm: 105, description: 'Jump bringing knees to chest' },
      { id: '9-4', name: 'Cable Woodchops', sets: 3, reps: 15, equipment: 'Cable', calories: 55, description: 'Diagonal chopping motion with cable' },
      { id: '9-5', name: 'Inchworms', sets: 3, reps: 12, equipment: 'Bodyweight', calories: 45, description: 'Walk hands out to plank and back' },
    ],
  },
  {
    day: 10,
    completed: false,
    targetCalories: 330,
    exercises: [
      { id: '10-1', name: 'Power Cleans', sets: 4, reps: 8, equipment: 'Barbell', calories: 85, description: 'Explosive lift from ground to shoulders' },
      { id: '10-2', name: 'Dumbbell Snatches', sets: 3, reps: 10, equipment: 'Dumbbell', calories: 70, description: 'Swing dumbbell from ground to overhead' },
      { id: '10-3', name: 'Box Step Overs', sets: 3, reps: 20, equipment: 'Box', calories: 65, bpm: 90, description: 'Step up and over box continuously' },
      { id: '10-4', name: 'Hanging Knee Raises', sets: 3, reps: 15, equipment: 'Bar', calories: 55, description: 'Raise knees to chest while hanging' },
      { id: '10-5', name: 'Bear Crawls', sets: 3, reps: 20, equipment: 'Bodyweight', calories: 55, description: 'Crawl on hands and feet, meters not reps' },
    ],
  },
  {
    day: 11,
    completed: false,
    targetCalories: 300,
    exercises: [
      { id: '11-1', name: 'Arnold Press', sets: 4, reps: 12, equipment: 'Dumbbells', calories: 65, description: 'Rotating shoulder press' },
      { id: '11-2', name: 'Pistol Squats', sets: 3, reps: 8, equipment: 'Bodyweight', calories: 60, description: 'Single leg squat, per leg' },
      { id: '11-3', name: 'Decline Push-ups', sets: 3, reps: 15, equipment: 'Bench', calories: 55, description: 'Push-ups with feet elevated' },
      { id: '11-4', name: 'Kettlebell Swings', sets: 3, reps: 20, equipment: 'Kettlebell', calories: 70, bpm: 100, description: 'Swing kettlebell between legs and to chest height' },
      { id: '11-5', name: 'Dragon Flags', sets: 3, reps: 8, equipment: 'Bench', calories: 50, description: 'Advanced core exercise keeping body straight' },
    ],
  },
  {
    day: 12,
    completed: false,
    targetCalories: 340,
    exercises: [
      { id: '12-1', name: 'Thrusters', sets: 4, reps: 12, equipment: 'Barbell', calories: 85, description: 'Squat and press barbell overhead in one motion' },
      { id: '12-2', name: 'Renegade Rows', sets: 3, reps: 12, equipment: 'Dumbbells', calories: 70, description: 'Plank position alternating rows' },
      { id: '12-3', name: 'Broad Jumps', sets: 3, reps: 10, equipment: 'Bodyweight', calories: 65, description: 'Jump forward as far as possible' },
      { id: '12-4', name: 'Medicine Ball Slams', sets: 3, reps: 15, equipment: 'Medicine Ball', calories: 75, bpm: 110, description: 'Lift ball overhead and slam down' },
      { id: '12-5', name: 'Windshield Wipers', sets: 3, reps: 10, equipment: 'Bodyweight', calories: 45, description: 'Rotate legs side to side while hanging or lying' },
    ],
  },
  {
    day: 13,
    completed: false,
    targetCalories: 350,
    exercises: [
      { id: '13-1', name: 'Front Squats', sets: 4, reps: 10, equipment: 'Barbell', calories: 85, description: 'Squat with barbell on front shoulders' },
      { id: '13-2', name: 'Muscle-ups', sets: 3, reps: 5, equipment: 'Bar', calories: 70, description: 'Pull-up transitioning to dip above bar' },
      { id: '13-3', name: 'Turkish Get-ups', sets: 3, reps: 6, equipment: 'Kettlebell', calories: 65, description: 'Complex movement from lying to standing with weight' },
      { id: '13-4', name: 'Burpee Box Jumps', sets: 3, reps: 10, equipment: 'Box', calories: 80, bpm: 100, description: 'Burpee followed by box jump' },
      { id: '13-5', name: 'L-sits', sets: 3, reps: 20, equipment: 'Bodyweight', calories: 50, description: 'Hold L position, seconds not reps' },
    ],
  },
  {
    day: 14,
    completed: false,
    targetCalories: 250,
    exercises: [
      { id: '14-1', name: 'Light Circuit', sets: 2, reps: 15, equipment: 'Bodyweight', calories: 100, description: 'Easy full body circuit for recovery' },
      { id: '14-2', name: 'Yoga Recovery', sets: 1, reps: 30, equipment: 'Bodyweight', calories: 70, description: 'Restorative yoga poses, minutes not reps' },
      { id: '14-3', name: 'Walking', sets: 1, reps: 20, equipment: 'Bodyweight', calories: 50, description: 'Light walking for active recovery, minutes not reps' },
      { id: '14-4', name: 'Deep Stretching', sets: 1, reps: 15, equipment: 'Bodyweight', calories: 30, description: 'Focus on tight muscle groups, minutes not reps' },
    ],
  },
];
