import { WorkoutDay } from '../types';

export const workoutProgram: WorkoutDay[] = [
  {
    day: 1,
    completed: false,
    targetCalories: 250,
    exercises: [
      { id: '1-1', name: 'Pompes', sets: 3, reps: 15, equipment: 'Poids du corps', calories: 45, description: 'Gardez le corps droit et descendez jusqu\'à ce que la poitrine touche presque le sol' },
      { id: '1-2', name: 'Squats', sets: 3, reps: 20, equipment: 'Poids du corps', calories: 55, description: 'Gardez le dos droit et descendez jusqu\'à ce que les cuisses soient parallèles au sol' },
      { id: '1-3', name: 'Planche', sets: 3, reps: 30, equipment: 'Poids du corps', calories: 40, description: 'Maintenez la position avec le corps en ligne droite, secondes au lieu de répétitions' },
      { id: '1-4', name: 'Jumping Jacks', sets: 3, reps: 25, equipment: 'Poids du corps', calories: 60, bpm: 120, description: 'Sautez en écartant bras et jambes, puis revenez en position debout' },
      { id: '1-5', name: 'Mountain Climbers', sets: 3, reps: 20, equipment: 'Poids du corps', calories: 50, bpm: 100, description: 'Alternez en ramenant les genoux vers la poitrine en position de planche' },
    ],
  },
  {
    day: 2,
    completed: false,
    targetCalories: 280,
    exercises: [
      { id: '2-1', name: 'Rowing haltères', sets: 4, reps: 12, equipment: 'Haltères', calories: 50, description: 'Tirez l\'haltère vers la hanche en étant penché' },
      { id: '2-2', name: 'Fentes', sets: 3, reps: 15, equipment: 'Poids du corps', calories: 55, description: 'Avancez et abaissez le genou arrière vers le sol' },
      { id: '2-3', name: 'Burpees', sets: 3, reps: 10, equipment: 'Poids du corps', calories: 70, bpm: 110, description: 'Descendez en position de pompe, ramenez les pieds puis sautez' },
      { id: '2-4', name: 'Crunchs vélo', sets: 3, reps: 20, equipment: 'Poids du corps', calories: 45, description: 'Alternez coude vers genou opposé en étant allongé sur le dos' },
      { id: '2-5', name: 'Montées de genoux', sets: 3, reps: 30, equipment: 'Poids du corps', calories: 60, bpm: 130, description: 'Courez sur place en montant les genoux haut' },
    ],
  },
  {
    day: 3,
    completed: false,
    targetCalories: 300,
    exercises: [
      { id: '3-1', name: 'Développé pectoraux', sets: 4, reps: 12, equipment: 'Haltères', calories: 60, description: 'Poussez les haltères vers le haut depuis le niveau de la poitrine' },
      { id: '3-2', name: 'Squats gobelet', sets: 4, reps: 15, equipment: 'Haltère', calories: 65, description: 'Tenez l\'haltère au niveau de la poitrine et faites un squat' },
      { id: '3-3', name: 'Russian twists', sets: 3, reps: 25, equipment: 'Poids du corps', calories: 50, description: 'Tournez le torse de gauche à droite en position assise' },
      { id: '3-4', name: 'Squats sautés', sets: 3, reps: 12, equipment: 'Poids du corps', calories: 65, bpm: 100, description: 'Faites un squat puis explosez vers le haut en sautant' },
      { id: '3-5', name: 'Superman', sets: 3, reps: 15, equipment: 'Poids du corps', calories: 40, description: 'Levez bras et jambes en étant allongé face contre terre' },
    ],
  },
  {
    day: 4,
    completed: false,
    targetCalories: 260,
    exercises: [
      { id: '4-1', name: 'Tractions', sets: 3, reps: 8, equipment: 'Barre', calories: 55, description: 'Tirez-vous jusqu\'à ce que le menton soit au-dessus de la barre' },
      { id: '4-2', name: 'Dips', sets: 3, reps: 12, equipment: 'Barre', calories: 50, description: 'Abaissez le corps en pliant les coudes, puis poussez vers le haut' },
      { id: '4-3', name: 'Chaise contre le mur', sets: 3, reps: 45, equipment: 'Poids du corps', calories: 45, description: 'Maintenez la position de squat contre le mur, secondes et non répétitions' },
      { id: '4-4', name: 'Planche latérale', sets: 3, reps: 30, equipment: 'Poids du corps', calories: 40, description: 'Maintenez la position latérale sur le coude, de chaque côté' },
      { id: '4-5', name: 'Sauts sur box', sets: 3, reps: 10, equipment: 'Box', calories: 70, description: 'Sautez sur une surface élevée et descendez' },
    ],
  },
  {
    day: 5,
    completed: false,
    targetCalories: 290,
    exercises: [
      { id: '5-1', name: 'Soulevé de terre', sets: 4, reps: 10, equipment: 'Barre', calories: 75, description: 'Soulevez la barre du sol jusqu\'à la position debout' },
      { id: '5-2', name: 'Développé épaules', sets: 3, reps: 12, equipment: 'Haltères', calories: 55, description: 'Poussez les haltères au-dessus de la tête depuis le niveau des épaules' },
      { id: '5-3', name: 'Relevés de jambes', sets: 3, reps: 15, equipment: 'Poids du corps', calories: 45, description: 'Levez les jambes en étant allongé sur le dos' },
      { id: '5-4', name: 'Patineurs', sets: 3, reps: 20, equipment: 'Poids du corps', calories: 60, bpm: 120, description: 'Sautez de côté à côté avec un mouvement de patineur' },
      { id: '5-5', name: 'Pompes pike', sets: 3, reps: 12, equipment: 'Poids du corps', calories: 55, description: 'Pompe avec les hanches levées haut' },
    ],
  },
  {
    day: 6,
    completed: false,
    targetCalories: 270,
    exercises: [
      { id: '6-1', name: 'Développé couché', sets: 4, reps: 10, equipment: 'Barre', calories: 70, description: 'Poussez la barre depuis la poitrine en étant allongé sur un banc' },
      { id: '6-2', name: 'Step-ups', sets: 3, reps: 15, equipment: 'Box', calories: 60, description: 'Montez sur une surface élevée en alternant les jambes' },
      { id: '6-3', name: 'V-ups', sets: 3, reps: 12, equipment: 'Poids du corps', calories: 50, description: 'Levez bras et jambes simultanément en forme de V' },
      { id: '6-4', name: 'Battle ropes', sets: 3, reps: 30, equipment: 'Cordes', calories: 65, bpm: 100, description: 'Créez des vagues avec des cordes lourdes' },
      { id: '6-5', name: 'Battements de jambes', sets: 3, reps: 30, equipment: 'Poids du corps', calories: 45, description: 'Alternez de petits coups de pieds en étant allongé' },
    ],
  },
  {
    day: 7,
    completed: false,
    targetCalories: 200,
    exercises: [
      { id: '7-1', name: 'Cardio léger', sets: 1, reps: 20, equipment: 'Poids du corps', calories: 80, description: 'Rythme facile pour récupération active, minutes et non répétitions' },
      { id: '7-2', name: 'Étirements', sets: 1, reps: 15, equipment: 'Poids du corps', calories: 30, description: 'Routine d\'étirements du corps entier, minutes et non répétitions' },
      { id: '7-3', name: 'Yoga flow', sets: 1, reps: 20, equipment: 'Poids du corps', calories: 60, description: 'Poses de yoga légères pour la flexibilité, minutes et non répétitions' },
      { id: '7-4', name: 'Rouleau de massage', sets: 1, reps: 10, equipment: 'Rouleau en mousse', calories: 30, description: 'Massez les muscles avec un rouleau en mousse, minutes et non répétitions' },
    ],
  },
  {
    day: 8,
    completed: false,
    targetCalories: 310,
    exercises: [
      { id: '8-1', name: 'Squats avec barre', sets: 4, reps: 12, equipment: 'Barre', calories: 80, description: 'Squat avec la barre sur les épaules' },
      { id: '8-2', name: 'Pompes inclinées', sets: 3, reps: 15, equipment: 'Banc', calories: 50, description: 'Pompes avec les mains sur une surface élevée' },
      { id: '8-3', name: 'Planche vers chien tête en bas', sets: 3, reps: 12, equipment: 'Poids du corps', calories: 45, description: 'Passez de la planche à la position du chien tête en bas' },
      { id: '8-4', name: 'Sauts étoile', sets: 3, reps: 15, equipment: 'Poids du corps', calories: 70, bpm: 115, description: 'Sautez avec bras et jambes formant une étoile' },
      { id: '8-5', name: 'Crunchs inversés', sets: 3, reps: 20, equipment: 'Poids du corps', calories: 45, description: 'Levez les hanches et les jambes vers la poitrine en étant allongé' },
    ],
  },
  {
    day: 9,
    completed: false,
    targetCalories: 320,
    exercises: [
      { id: '9-1', name: 'Rowing barre penché', sets: 4, reps: 12, equipment: 'Barre', calories: 65, description: 'Tirez la barre vers la poitrine en étant penché' },
      { id: '9-2', name: 'Squats bulgares', sets: 3, reps: 12, equipment: 'Haltères', calories: 70, description: 'Fente avec le pied arrière élevé' },
      { id: '9-3', name: 'Sauts groupés', sets: 3, reps: 10, equipment: 'Poids du corps', calories: 75, bpm: 105, description: 'Sautez en ramenant les genoux vers la poitrine' },
      { id: '9-4', name: 'Bûcheron au câble', sets: 3, reps: 15, equipment: 'Câble', calories: 55, description: 'Mouvement de hache en diagonal avec câble' },
      { id: '9-5', name: 'Vers de terre', sets: 3, reps: 12, equipment: 'Poids du corps', calories: 45, description: 'Marchez avec les mains vers la planche et revenez' },
    ],
  },
  {
    day: 10,
    completed: false,
    targetCalories: 330,
    exercises: [
      { id: '10-1', name: 'Power Cleans', sets: 4, reps: 8, equipment: 'Barbell', calories: 85, description: 'Explosive lift from ground to shoulders' },
      { id: '10-2', name: 'Dumbbell Snatches', sets: 3, reps: 10, equipment: 'Dumbbell', calories: 70, description: 'Swing dumbbell from ground to overhead' },
      { id: '10-3', name: 'Box Step Overs', sets: 3, reps: 20, equipment: 'Box', calories: 65, bpm: 90, description: 'Step up and over box continuously' },
      { id: '10-4', name: 'Hanging Knee Raises', sets: 3, reps: 15, equipment: 'Bar', calories: 55, description: 'Raise knees to chest while hanging' },
      { id: '10-5', name: 'Bear Crawls', sets: 3, reps: 20, equipment: 'Bodyweight', calories: 55, description: 'Crawl on hands and feet, meters not reps' },
    ],
  },
  {
    day: 11,
    completed: false,
    targetCalories: 300,
    exercises: [
      { id: '11-1', name: 'Arnold Press', sets: 4, reps: 12, equipment: 'Dumbbells', calories: 65, description: 'Rotating shoulder press' },
      { id: '11-2', name: 'Pistol Squats', sets: 3, reps: 8, equipment: 'Bodyweight', calories: 60, description: 'Single leg squat, per leg' },
      { id: '11-3', name: 'Decline Push-ups', sets: 3, reps: 15, equipment: 'Bench', calories: 55, description: 'Push-ups with feet elevated' },
      { id: '11-4', name: 'Kettlebell Swings', sets: 3, reps: 20, equipment: 'Kettlebell', calories: 70, bpm: 100, description: 'Swing kettlebell between legs and to chest height' },
      { id: '11-5', name: 'Dragon Flags', sets: 3, reps: 8, equipment: 'Bench', calories: 50, description: 'Advanced core exercise keeping body straight' },
    ],
  },
  {
    day: 12,
    completed: false,
    targetCalories: 340,
    exercises: [
      { id: '12-1', name: 'Thrusters', sets: 4, reps: 12, equipment: 'Barbell', calories: 85, description: 'Squat and press barbell overhead in one motion' },
      { id: '12-2', name: 'Renegade Rows', sets: 3, reps: 12, equipment: 'Dumbbells', calories: 70, description: 'Plank position alternating rows' },
      { id: '12-3', name: 'Broad Jumps', sets: 3, reps: 10, equipment: 'Bodyweight', calories: 65, description: 'Jump forward as far as possible' },
      { id: '12-4', name: 'Medicine Ball Slams', sets: 3, reps: 15, equipment: 'Medicine Ball', calories: 75, bpm: 110, description: 'Lift ball overhead and slam down' },
      { id: '12-5', name: 'Windshield Wipers', sets: 3, reps: 10, equipment: 'Bodyweight', calories: 45, description: 'Rotate legs side to side while hanging or lying' },
    ],
  },
  {
    day: 13,
    completed: false,
    targetCalories: 350,
    exercises: [
      { id: '13-1', name: 'Front Squats', sets: 4, reps: 10, equipment: 'Barbell', calories: 85, description: 'Squat with barbell on front shoulders' },
      { id: '13-2', name: 'Muscle-ups', sets: 3, reps: 5, equipment: 'Bar', calories: 70, description: 'Pull-up transitioning to dip above bar' },
      { id: '13-3', name: 'Turkish Get-ups', sets: 3, reps: 6, equipment: 'Kettlebell', calories: 65, description: 'Complex movement from lying to standing with weight' },
      { id: '13-4', name: 'Burpee Box Jumps', sets: 3, reps: 10, equipment: 'Box', calories: 80, bpm: 100, description: 'Burpee followed by box jump' },
      { id: '13-5', name: 'L-sits', sets: 3, reps: 20, equipment: 'Bodyweight', calories: 50, description: 'Hold L position, seconds not reps' },
    ],
  },
  {
    day: 14,
    completed: false,
    targetCalories: 250,
    exercises: [
      { id: '14-1', name: 'Light Circuit', sets: 2, reps: 15, equipment: 'Bodyweight', calories: 100, description: 'Easy full body circuit for recovery' },
      { id: '14-2', name: 'Yoga Recovery', sets: 1, reps: 30, equipment: 'Bodyweight', calories: 70, description: 'Restorative yoga poses, minutes not reps' },
      { id: '14-3', name: 'Walking', sets: 1, reps: 20, equipment: 'Bodyweight', calories: 50, description: 'Light walking for active recovery, minutes not reps' },
      { id: '14-4', name: 'Deep Stretching', sets: 1, reps: 15, equipment: 'Bodyweight', calories: 30, description: 'Focus on tight muscle groups, minutes not reps' },
    ],
  },
];
